name: Saurabh Portfolio

on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-access-access-key: ${{ secrets.AWS_ACCESS_KEY }}
        aws-region: us-est-1
    
    - name: Deploy static site to S3 bucket
      run: aws s3 sync . s3://saurabh-portfolio --delete
